# Generated by Django 4.2.23 on 2025-10-07 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'آقا'), ('F', 'خانم')], max_length=1)),
                ('student_number', models.CharField(max_length=20, unique=True)),
                ('education_level', models.CharField(choices=[('BSc', 'کارشناسی'), ('MSc', 'کارشناسی ارشد'), ('PhD', 'دکتری')], max_length=100)),
                ('field_of_study', models.CharField(max_length=200)),
                ('national_id', models.CharField(max_length=10, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('previous_semester_transcript', models.FileField(blank=True, null=True, upload_to='transcripts/')),
                ('one_year_plan_for_association', models.FileField(blank=True, null=True, upload_to='one_year_plan/')),
                ('student_id_card', models.ImageField(blank=True, null=True, upload_to='student_id_cards/')),
                ('personal_photo', models.ImageField(upload_to='personal_photos/')),
                ('election_photo', models.ImageField(blank=True, null=True, upload_to='election_photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('candidate_code', models.IntegerField(unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('candidate'), models.Model),
        ),
        migrations.CreateModel(
            name='ScientificAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='association_logos/')),
                ('valid', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('scientific_association'), models.Model),
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'آقا'), ('F', 'خانم')], max_length=1)),
                ('fathers_name', models.CharField(max_length=100)),
                ('education_level', models.CharField(choices=[('BSc', 'کارشناسی'), ('MSc', 'کارشناسی ارشد'), ('PhD', 'دکتری')], max_length=100)),
                ('national_id', models.CharField(max_length=10)),
                ('field_of_study', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('student_number', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('voted', models.BooleanField(default=False)),
                ('confirmed_information', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('scientific_association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.scientificassociation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('voter'), models.Model),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmation_code', models.CharField(blank=True, editable=False, max_length=16, unique=True)),
                ('ip_address', models.GenericIPAddressField(editable=False)),
                ('user_agent', models.CharField(editable=False, max_length=255)),
                ('device', models.CharField(editable=False, max_length=255)),
                ('valid', models.BooleanField(default=True)),
                ('candidate', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='vote.candidate')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='vote.voter')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('votew'), models.Model),
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_token', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('otp_sent', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.voter')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('otp'), models.Model),
        ),
        migrations.AddField(
            model_name='candidate',
            name='scientific_association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vote.scientificassociation'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(fields=('national_id', 'scientific_association'), name='unique_national_id_per_association', violation_error_message='کاربری با این کد ملی در این انجمن قبلا ثبت شده است.'),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(fields=('student_number', 'scientific_association'), name='unique_student_number_per_association', violation_error_message='کاربری با این شماره دانشجویی در این انجمن قبلا ثبت شده است.'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'candidate'), name='unique_vote_per_voter_candidate'),
        ),
    ]
